### ISSUE TITLE
If a non PTE/GTE adds a comment no warning is shown

### ISSUE THREAD

**Issue by psmits1567** [amieiro/translate-w-org-env#2]
I think the handling of submitting comments needs improvement
In the following situations, clicking the Post Comment button does not show warnings
1. Empty translation
2. Translation entered but not saved
3. If no topic is selected
4. translation suggested and reopened.

If an admin submits a comment it also needs improvement, no warning shown
1. No topic selected.

**Comment by amieiro** [comment]
I move this issue to [other repo](https://github.com/GlotPress/gp-translation-helpers/issues/17).
